Added example for dfs namespace
Azure/azurehpc pull request #386
Opened 2020-09-29 17:47 UTC by edwardsp

2020-09-29 18:13 UTC, xpillons requested changes
please remove hardcoded password

2020-09-29 18:13 UTC, xpillons commented on examples/dfs_namespace/anf-config.json
> +      "ad_password": "Microsoft123!",
can you please not store password here

2020-09-29 21:38 UTC, edwardsp commented on examples/dfs_namespace/anf-config.json
> +      "ad_password": "Microsoft123!",
done

2020-09-30 07:23 UTC, xpillons approved these changes

2020-09-30 08:21 UTC, merged