Create run.spectre
Azure/azurehpc pull request #397
Opened 2020-10-19 04:03 UTC by mengruts

2020-10-19 04:03 UTC, mengruts commented
@hmeiland can you help review my pr? Thanks.

2020-12-15 12:06 UTC, xpillons commented
@mengruts @hmeiland is this still valid ? if so please review, merge and delete the branch.

2021-01-22 08:31 UTC, xpillons requested changes
Please make the IP a parameter and not a hardcoded value, especially if it's a public one

2021-01-22 11:24 UTC, xpillons approved these changes

2021-05-24 10:08 UTC, merged